-- Create the table to store progress for each user in each series
CREATE TABLE IF NOT EXISTS public.series_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    series_slug TEXT NOT NULL,
    read_posts_slugs TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT series_progress_user_id_series_slug_key UNIQUE (user_id, series_slug)
);

-- Enable Row Level Security if not already enabled
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'series_progress' AND n.nspname = 'public' AND c.relrowsecurity
    ) THEN
        ALTER TABLE public.series_progress ENABLE ROW LEVEL SECURITY;
    END IF;
END $$;


-- Drop existing policies before creating them to ensure idempotency
DROP POLICY IF EXISTS "Users can view their own series progress" ON public.series_progress;
CREATE POLICY "Users can view their own series progress"
ON public.series_progress
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own series progress" ON public.series_progress;
CREATE POLICY "Users can insert their own series progress"
ON public.series_progress
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own series progress" ON public.series_progress;
CREATE POLICY "Users can update their own series progress"
ON public.series_progress
FOR UPDATE
USING (auth.uid() = user_id);

-- Function and Trigger to update the 'updated_at' timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_series_progress_updated ON public.series_progress;
CREATE TRIGGER on_series_progress_updated
BEFORE UPDATE ON public.series_progress
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();
